version: '3'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - database

  database:
    image: mysql:latest
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: teamsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: pw
    ports:
      - "3306:3306"