version: '3'

services:
  mysqlserver:
    image: mysql/mysql-server
    container_name: mysqlserver
    volumes:
      - datafiles:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: teamdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
  api-services:
    build: .
    ports: 
      - 8080:80

volumes:
  datafiles:
